# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6.xci
# IP: The module: 'design_1_axi_gpio_1_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6.xci
# IP: The module: 'design_1_axi_gpio_1_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
