# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_9/design_1_microblaze_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_9 || ORIG_REF_NAME==design_1_microblaze_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PmodOLEDrgb_0_6/design_1_PmodOLEDrgb_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PmodOLEDrgb_0_6 || ORIG_REF_NAME==design_1_PmodOLEDrgb_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_6 || ORIG_REF_NAME==design_1_axi_gpio_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_6/design_1_axi_uartlite_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_6 || ORIG_REF_NAME==design_1_axi_uartlite_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_6/design_1_axi_gpio_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_6 || ORIG_REF_NAME==design_1_axi_gpio_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_9/design_1_dlmb_v10_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_9 || ORIG_REF_NAME==design_1_dlmb_v10_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_9/design_1_ilmb_v10_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_9 || ORIG_REF_NAME==design_1_ilmb_v10_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_9/design_1_dlmb_bram_if_cntlr_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_9 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_9/design_1_ilmb_bram_if_cntlr_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_9 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_9/design_1_lmb_bram_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_9 || ORIG_REF_NAME==design_1_lmb_bram_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_8/design_1_xbar_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_8 || ORIG_REF_NAME==design_1_xbar_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_9/design_1_microblaze_0_axi_periph_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_9 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_7/design_1_microblaze_0_axi_intc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_7 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_7/design_1_microblaze_0_xlconcat_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_7 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_9/design_1_mdm_1_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_9 || ORIG_REF_NAME==design_1_mdm_1_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# XDC: d:/Bruh_ELE_ELECTRONIC_ENGINEERING-B_LAB/Lab06-Project/Lab6_JumpBlock/Lab6_JumpBlock.gen/sources_1/bd/design_1/design_1_ooc.xdc
